### ISSUE TITLE
Use params info to verify values of vars in ```add_run()```

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#81] opened 2019-05-09 09:38 UTC
The params dict each app class has can contain e.g. ```min``` and ```max``` values that parameter can take. At present this is not used for verification of var values in the campaign's ```add_run()``` method.

**Comment by dww100** [comment] 2019-05-22 10:09
Duplicate of #51

**Closed** 2019-05-22 10:09 UTC
