### ISSUE TITLE
Support distributions not in Chaospy

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#69] opened 2019-04-03 09:48 UTC
The two cases we have identified so far are:
- [x] Custom distribution from histogram 
- [x] Discrete distribution (`uniform_integer`) which we need, for example, to make random seeds

**Comment by dww100** [comment] 2019-04-03 09:52
@djgroen Suggested developing from here:
https://chaospy.readthedocs.io/en/master/distributions/custom.html

**Comment by jlakhlili** [comment] 2019-04-03 14:13
Another case : 

- [ ] Reformulated distribution from dependent random variables.

I already had gathered some documentations about transformations to uncorrelated standard variables [eg.: 1, 2].  We will need it, because one of the underlying assumptions when expanding  polynomial chaos and stochastic collocation is that the model parameters are independents, So, we have to create reformulated distribution based on an independents set result of the decorrelation procedures. 

I also wrote an AUC about this point : 
https://github.com/vecma-project/VECMA-AUCs/blob/master/fusion/output_distribution.md

[1] https://arxiv.org/abs/1903.09682
[2] https://doi.org/10.2514/6.2009-976

**Comment by raar1** [comment] 2019-04-03 15:20
I suggest we add these custom implementations to the distributions directory in EasyVVUQ when we get round to creating them

**Comment by raar1** [comment] 2019-05-08 11:19
@jlakhlili If you get around to doing this (custom chaospy distribution) then could you add some brief documentation to the wiki on how you did it? (what was important to actually implement etc)

**Comment by dww100** [comment] 2019-05-28 17:46
@jlakhlili have you looked into this at all. We would really like a `uniform_integer` function.

**Comment by jlakhlili** [comment] 2019-05-29 14:17
@dww100 I did another thing with a module called `decorrelate` where I generate a new output distribution using `chaospy.QoI_Dist`. I will show this work in the ICCS to @raar1  and see where we can fit it in the code. Maybe under `elements` in the same level as `collate`.
But, I didn't look at 'uniform_integer' for the moment. I will also prepare it and discuss about it during the ICCS.

**Comment by jlakhlili** [comment] 2019-05-29 14:21
I just saw the code. Many changes are done.

**Comment by jlakhlili** [comment] 2019-06-14 14:11
Done. Please check.

**Comment by jonathf** [comment] 2019-08-14 20:22
As discussed in #131, it might be a good idea to make a native distribution in chaospy covering your usecase when it makes sense.

@jlakhlili, I hope you don't mind. I expanded upon your proposed descrete uniform code to how the code works inside chaospy. A PR for the code I am proposing here:
https://github.com/jonathf/chaospy/pull/163
Feel free to test to see if it works out.

**Comment by jlakhlili** [comment] 2019-08-16 16:23
You are welcome.
I've seen that you have added a new class `DiscreteUniform`. I will test it as soon as possible and come back to you.

**Comment by jonathf** [comment] 2019-08-25 08:51
This issue addresses two more types of distributions that you need for your project.

First, `chaospy` has support for dependent random variables. Long over due, but I finally got around to create a small write-up on the topic:
https://chaospy.readthedocs.io/en/master/recipes/dependent.html
I also wrote a journal article on the topic, if you need something more formal:
https://epubs.siam.org/doi/10.1137/15M1020447
Let me know if it is of any use to you.

Second, the histogram distribution sounds interesting. Can someone describe what that would look like? I might be able to create it as well.

**Comment by raar1** [comment] 2019-09-16 13:05
@jonathf thanks for this and the links, it could be useful.

I suppose the histogram distribution we were thinking of was intended as a representation for a "general distribution", one not necessarily fitting any of the analytically defined standard distributions. Ocassionaly we have results which are distributed in such a fashion, and which are used as input to another solver further down the workflow. Rather than force the distribution into e.g. a gaussian we might like to try sampling from (as closely as possible) the actual measured distribution. Whether or not this will prove to be a good idea in practice is, of course, a different matter...

I understand that with chaospy this sort of distribution might not be compatible with some sampling techniques? For example, identifying or using the orthogonal distribution to such a general distribution might not be sensible or possible. I'm not sure what the extent of the problem would be, though.

**Comment by raar1** [comment] 2019-09-19 10:56
@jlakhlili Did you have any luck with the ```DiscreteUniform``` testing? If it's covered by chaospy then we can remove our version from EasyVVUQ.

**Comment by raar1** [comment] 2019-09-20 10:14
@jonathf Thanks, this looks more or less like what we meant by the "histogram" case. Kernel density would likely be fine for our expected use cases.

**Comment by raar1** [comment] 2019-10-09 19:21
@jlakhlili Any luck with the ```DiscreteUniform``` distribution in chaospy yet?

**Comment by jlakhlili** [comment] 2019-10-10 12:25
Sorry for my non reactions until now.

**Comment by jlakhlili** [comment] 2019-10-10 12:40
The EasyVVUQ `uniform_integer`  distribution make random *integer  seeds* but `DiscreteUniform`  does not. It is operates on intervals of integers by rounding lower and upper values to the closed integers.  Here is an example:
``` python
In [1]: import chaospy, easyvvuq
In [2]: dist_ez = easyvvuq.distributions.uniform_integer(0, 100)
In [3]: dist_cp = chaospy.DiscreteUniform(0, 100)
In [4]: dist_ez.sample()
Out[4]: array(45)
In [5]: dist_cp.sample()
Out[5]: array(79.)
```
And the last

**Comment by jonathf** [comment] 2019-10-10 15:49
@jlakhlili, understandable. Unfortunately, one of the fundamental building blocks in chaospy relies on the random variable to be defined on the `(0,1)^D` hypercube and mapping the values from there. So there is no getting around the rounding rule that I use to get discrete variables in this space.

However, there is no reason why not the discrete variables couldn't return integer values. For example, I don't mind merging in something like this:
https://github.com/jonathf/chaospy/pull/173

**Comment by jlakhlili** [comment] 2019-10-21 11:03
That's what we need. Thanks. With the new parameter `interpret_as_integer`  witch is to True for DiscreteUniform we can replace  then `uniform_integer`

**Comment by jonathf** [comment] 2019-10-21 11:14
Good.
Merged now. 3.0.14 released.

**Comment by dww100** [comment] 2019-11-20 08:45
@wedeling I see in the comments of the code (and the accepted pull request above) that the `legendre` function is now redundant. Do you still have any code that uses it? If not then I think @orbitfold should remove it.

**Comment by raar1** [comment] 2019-12-10 14:07
@wedeling @orbitfold Just checking on Dave's question above. Can/has the ```legendre``` function been removed?

**Comment by dww100** [comment] 2019-12-10 14:50
I believe I have already?

**Comment by raar1** [comment] 2019-12-10 14:56
Well grep isn't finding anything, so I'm going to close this old issue now.

**Closed by raar1** 2019-12-10 14:56 UTC
