### ISSUE TITLE
Vector-valued QoI

### ISSUE THREAD

**Issue by fjansson** [UCL-CCS/EasyVVUQ#209] opened 2020-03-18 16:08 UTC
The JSON decoder supports vector-valued QoI, one in JSON one can simply assign a list of values to a variable.

The analysis functions do not handle vector QoI yet. Part of the problem is the representation of vectors in the pandas dataframe - currently vectors are stored as strings.

Test case proposal: https://github.com/UCL-CCS/EasyVVUQ/pull/208

**Comment by orbitfold** [comment] 2020-03-20 16:53
I have investigated a bit. And right now I think that this is caused by the way pandas DataFrame.to_sql method handles things. Which we cannot really change. So what we need to do is probably re-implement how vector quantities are stored in data frames and pray that then that method works.

**Comment by orbitfold** [comment] 2020-05-15 15:44
Can we close this?

**Comment by fjansson** [comment] 2020-05-18 11:54
I'll test again, will let you know. It may take me a couple of days, I have to do something else first.

**Closed** 2021-02-08 10:45 UTC
